from openjdk:21-jdk-slim AS build
COPY pom.mvnw ./
COPY .mvn .mvn
RUN ./mvnw dependency:resolve

COPY src src
RUN ./mvnw package

FROM openjdk:21-jdk-slim
WORKDIR open-weather
COPY --from=build target/*.jar open-weather.jar
ENTRYPOINT ["jva","-jar","open-weather.jar"]